#!/usr/bin/env python3

# TODO
import os
import sys

import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # validate screen_name
    screen_name = sys.argv[1].lstrip("@")
    if not screen_name:
        sys.exit("Usage: ./tweets @screen_name")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get screen_name's tweets
    tweets = helpers.get_user_timeline(screen_name, 50)
    
    # analyze tweets
    for t in tweets:
        score = analyzer.analyze(t)
        if score > 0.0:
            print(colored("{:2d} {}".format(score, t), "green"))
        elif score < 0.0:
            print(colored("{:2d} {}".format(score, t), "red"))
        else:
            print(colored("{:2d} {}".format(score, t), "yellow"))


if __name__ == "__main__":
    main()
